version: "3"

services:
  app:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - RESTARTABLE=yes
    volumes:
      - "/data/dockerized/jupyter/notebooks:/home/jovyan/work"
      - "/data/dockerized/jupyter/jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.rule=Host(`notebook.tft`)"
      - "traefik.http.routers.jupyter.entrypoints=websecure"
      - "traefik.http.routers.jupyter.tls=true"
      - "traefik.http.routers.jupyter.tls.certresolver=myresolver"
      - "traefik.http.routers.jupyter.service=jupyter"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
      - "traefik.http.middlewares.jupyter.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.jupyter.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.jupyter.headers.stsPreload=true"
      - "traefik.http.middlewares.jupyter.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.jupyter.headers.contentSecurityPolicy=frame-ancestors 'self' *.tft"
      - "traefik.http.middlewares.jupyter.headers.customFrameOptionsValue=SAMEORIGIN"
    networks:
      - internal

networks:
  internal:
    external:
      name: internal
